If the JSSE jars are not present, we get a NoClassDefFoundError which is a Throwable.
git-svn-id: https://svn.apache.org/repos/asf/tomcat@284176 13f79535-47bb-0310-9956-ffa450edef68