Fix NPE exception when an invalid war file is deployed:
java.lang.NullPointerException
    at org.apache.catalina.loader.WebappLoader.closeJARs(WebappLoader.java:560)
    at org.apache.catalina.core.StandardContext.start(StandardContext.java:4140)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.

which cause:

java.io.IOException: java.lang.NullPointerException
    at org.apache.catalina.core.StandardHostDeployer.install(StandardHostDepl


git-svn-id: https://svn.apache.org/repos/asf/tomcat/container/catalina/trunk@301969 13f79535-47bb-0310-9956-ffa450edef68