- Make the notifier qn inner class, because of strange problems when using   JDK 1.4. The code is simpler that way, but I don't undestand the failure I got   (and why I don't get it with the inner class).   The stack trace was (against rev 1.21 of WebappLoader): WebappClassLoader:   Resource '/WEB-INF/classes/HelloWorldExample.class' was modified; Date is now: Fri Jan 04 17:48:04 CET 2002 Was: Fri Jan 04 14:48:08 CET 2002 java.lang.NoClassDefFoundError: org/apache/catalina/loader/WebappContextNotifier         at org.apache.catalina.loader.WebappLoader.notifyContext(WebappLoader.java:792)         at org.apache.catalina.loader.WebappLoader.run(WebappLoader.java:1286)         at java.lang.Thread.run(Thread.java:539)
git-svn-id: https://svn.apache.org/repos/asf/tomcat@287288 13f79535-47bb-0310-9956-ffa450edef68