Log warning when XML prolog cannot be parsed.
The 2 JSP TCK failures reported by Jeanfrancois are due to this, with
this root cause:

  java.lang.ClassNotFoundException: org.apache.xerces.util.SymbolTable


git-svn-id: https://svn.apache.org/repos/asf/tomcat@306084 13f79535-47bb-0310-9956-ffa450edef68